name: analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - astropy=4.0.2
  - async_generator=1.10
  - attrs=20.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0=openblas
  - bleach=3.1.5
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.2
  - cloudpickle=1.6.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.26.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - enum34=1.1.10
  - expat=2.2.9
  - ffmpeg=4.2.3
  - fontconfig=2.13.1
  - freetype=2.10.2
  - geos=3.8.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.65.0
  - gmp=6.2.0
  - gnutls=3.6.13
  - graphite2=1.3.13
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - icu=58.2
  - imagecodecs-lite=2019.12.3
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0=0
  # - ipykernel=5.3.4
  # - ipython=5.8.0
  # - ipython_genutils=0.2.0
  # - ipywidgets=7.5.1
  - jasper=1.900.1
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9d
  - jsonschema=3.2.0
  # - jupyter_client=6.1.7
  # - jupyter_contrib_core=0.3.3
  # - jupyter_contrib_nbextensions=0.5.1
  # - jupyter_core=4.6.3
  # - jupyter_highlight_selected_word=0.2.0
  # - jupyter_latex_envs=1.4.6
  # - jupyter_nbextensions_configurator=0.4.1
  # - jupyterlab_pygments=0.1.1
  - kiwisolver=1.2.0
  - lame=3.100
  - lcms2=2.11
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcxx=10.0.0=1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libopenblas=0.3.10
  - libopencv=4.2.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.12
  - libxslt=1.1.34
  - line_profiler=2.1.2
  - llvm-openmp=10.0.1
  - lxml=3.8.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1=1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  # - nbclient=0.5.0
  # - nbconvert=6.0.1
  # - nbformat=5.0.7
  - ncurses=6.2
  - nest-asyncio=1.4.0
  - nettle=3.4.1
  - networkx=2.5
  - notebook=6.1.4
  - numpy=1.19.1
  - olefile=0.46
  - opencv=4.2.0
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=20.4
  - pandas=1.1.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pathlib=1.0.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.38.0
  - prometheus_client=0.8.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - py-opencv=4.2.0
  - pycparser=2.20
  - pygments=2.7.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.2
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - readline=8.0
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2019.7.26.2
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.49.0
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - x264=1!152.20180806
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
      - colorcet==3.0.0
      - husl==4.0.3
      - iniconfig==1.1.1
      - neo==0.8.0
      - nose==1.3.7
      - numexpr==2.7.3
      - param==1.12.0
      - pluggy==1.0.0
      - py==1.11.0
      - pyabf==2.3.5
      - pycircstat==0.0.2
      - pyct==0.4.8
      - pyqtgraph==0.11.1
      - pytest==7.0.1
      - quantities==0.12.4
      - simplification==0.5.7
      - tables==3.6.1
      - tomli==1.2.3
